package cn.sirbox.dao;

import cn.sirbox.model.Part;
import cn.sirbox.model.PartExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    int countByExample(PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    int deleteByExample(PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    @Delete({
        "delete from part",
        "where pid = #{pid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    @Insert({
        "insert into part (pid, pname, ",
        "enabled, createtime, ",
        "updatetime)",
        "values (#{pid,jdbcType=INTEGER}, #{pname,jdbcType=VARCHAR}, ",
        "#{enabled,jdbcType=INTEGER}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(Part record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    int insertSelective(Part record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    List<Part> selectByExample(PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "pid, pname, enabled, createtime, updatetime",
        "from part",
        "where pid = #{pid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Part selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Part record, @Param("example") PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Part record, @Param("example") PartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Part record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated
     */
    @Update({
        "update part",
        "set pname = #{pname,jdbcType=VARCHAR},",
          "enabled = #{enabled,jdbcType=INTEGER},",
          "createtime = #{createtime,jdbcType=TIMESTAMP},",
          "updatetime = #{updatetime,jdbcType=TIMESTAMP}",
        "where pid = #{pid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Part record);
}