package cn.sirbox.dao;

import cn.sirbox.model.UserPartExample;
import cn.sirbox.model.UserPartKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface UserPartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_part
     *
     * @mbggenerated
     */
    int countByExample(UserPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_part
     *
     * @mbggenerated
     */
    int deleteByExample(UserPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_part
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_part",
        "where uid = #{uid,jdbcType=INTEGER}",
          "and pid = #{pid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UserPartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_part
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_part (uid, pid)",
        "values (#{uid,jdbcType=INTEGER}, #{pid,jdbcType=INTEGER})"
    })
    int insert(UserPartKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_part
     *
     * @mbggenerated
     */
    int insertSelective(UserPartKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_part
     *
     * @mbggenerated
     */
    List<UserPartKey> selectByExample(UserPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_part
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPartKey record, @Param("example") UserPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_part
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPartKey record, @Param("example") UserPartExample example);

    void insertUserPart(@Param("uid")Integer uid, @Param("pid")Integer pid);
}