package cn.sirbox.dao;

import cn.sirbox.model.DeptEnterpriseExample;
import cn.sirbox.model.DeptEnterpriseKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface DeptEnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_enterprise
     *
     * @mbggenerated
     */
    int countByExample(DeptEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_enterprise
     *
     * @mbggenerated
     */
    int deleteByExample(DeptEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_enterprise
     *
     * @mbggenerated
     */
    @Delete({
        "delete from dept_enterprise",
        "where did = #{did,jdbcType=INTEGER}",
          "and eid = #{eid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(DeptEnterpriseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_enterprise
     *
     * @mbggenerated
     */
    @Insert({
        "insert into dept_enterprise (did, eid)",
        "values (#{did,jdbcType=INTEGER}, #{eid,jdbcType=INTEGER})"
    })
    int insert(DeptEnterpriseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_enterprise
     *
     * @mbggenerated
     */
    int insertSelective(DeptEnterpriseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_enterprise
     *
     * @mbggenerated
     */
    List<DeptEnterpriseKey> selectByExample(DeptEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_enterprise
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeptEnterpriseKey record, @Param("example") DeptEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_enterprise
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeptEnterpriseKey record, @Param("example") DeptEnterpriseExample example);
}