package cn.sirbox.dao;

import cn.sirbox.model.Enterprise;
import cn.sirbox.model.EnterpriseExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    int countByExample(EnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    int deleteByExample(EnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    @Delete({
        "delete from enterprise",
        "where eid = #{eid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    @Insert({
        "insert into enterprise (eid, enabled, ",
        "estatus, ename, ",
        "ebusines, ebusiness, ",
        "ete, etex, eaddress, ",
        "eamount, elegal, etime, ",
        "erange, econtacts, ",
        "ephone, etelephone1, ",
        "etelephone2, etelephone3, ",
        "eemail, eintention, ",
        "etype, efinancingbegin, ",
        "efinancingout, createtime, ",
        "updatetime)",
        "values (#{eid,jdbcType=INTEGER}, #{enabled,jdbcType=INTEGER}, ",
        "#{estatus,jdbcType=INTEGER}, #{ename,jdbcType=VARCHAR}, ",
        "#{ebusines,jdbcType=VARCHAR}, #{ebusiness,jdbcType=VARCHAR}, ",
        "#{ete,jdbcType=VARCHAR}, #{etex,jdbcType=VARCHAR}, #{eaddress,jdbcType=VARCHAR}, ",
        "#{eamount,jdbcType=REAL}, #{elegal,jdbcType=VARCHAR}, #{etime,jdbcType=TIMESTAMP}, ",
        "#{erange,jdbcType=VARCHAR}, #{econtacts,jdbcType=VARCHAR}, ",
        "#{ephone,jdbcType=VARCHAR}, #{etelephone1,jdbcType=VARCHAR}, ",
        "#{etelephone2,jdbcType=VARCHAR}, #{etelephone3,jdbcType=VARCHAR}, ",
        "#{eemail,jdbcType=VARCHAR}, #{eintention,jdbcType=VARCHAR}, ",
        "#{etype,jdbcType=VARCHAR}, #{efinancingbegin,jdbcType=REAL}, ",
        "#{efinancingout,jdbcType=REAL}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(Enterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    int insertSelective(Enterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    List<Enterprise> selectByExample(EnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "eid, enabled, estatus, ename, ebusines, ebusiness, ete, etex, eaddress, eamount, ",
        "elegal, etime, erange, econtacts, ephone, etelephone1, etelephone2, etelephone3, ",
        "eemail, eintention, etype, efinancingbegin, efinancingout, createtime, updatetime",
        "from enterprise",
        "where eid = #{eid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Enterprise selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Enterprise record, @Param("example") EnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Enterprise record, @Param("example") EnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Enterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbggenerated
     */
    @Update({
        "update enterprise",
        "set enabled = #{enabled,jdbcType=INTEGER},",
          "estatus = #{estatus,jdbcType=INTEGER},",
          "ename = #{ename,jdbcType=VARCHAR},",
          "ebusines = #{ebusines,jdbcType=VARCHAR},",
          "ebusiness = #{ebusiness,jdbcType=VARCHAR},",
          "ete = #{ete,jdbcType=VARCHAR},",
          "etex = #{etex,jdbcType=VARCHAR},",
          "eaddress = #{eaddress,jdbcType=VARCHAR},",
          "eamount = #{eamount,jdbcType=REAL},",
          "elegal = #{elegal,jdbcType=VARCHAR},",
          "etime = #{etime,jdbcType=TIMESTAMP},",
          "erange = #{erange,jdbcType=VARCHAR},",
          "econtacts = #{econtacts,jdbcType=VARCHAR},",
          "ephone = #{ephone,jdbcType=VARCHAR},",
          "etelephone1 = #{etelephone1,jdbcType=VARCHAR},",
          "etelephone2 = #{etelephone2,jdbcType=VARCHAR},",
          "etelephone3 = #{etelephone3,jdbcType=VARCHAR},",
          "eemail = #{eemail,jdbcType=VARCHAR},",
          "eintention = #{eintention,jdbcType=VARCHAR},",
          "etype = #{etype,jdbcType=VARCHAR},",
          "efinancingbegin = #{efinancingbegin,jdbcType=REAL},",
          "efinancingout = #{efinancingout,jdbcType=REAL},",
          "createtime = #{createtime,jdbcType=TIMESTAMP},",
          "updatetime = #{updatetime,jdbcType=TIMESTAMP}",
        "where eid = #{eid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Enterprise record);

    List<Enterprise> selectAllEnterprise(@Param("thispage")Integer thispage, @Param
            ("pagenumber")Integer pagenumber);

    int insertLastId();
}