package cn.sirbox.dao;

import cn.sirbox.model.PartRoleExample;
import cn.sirbox.model.PartRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface PartRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_role
     *
     * @mbggenerated
     */
    int countByExample(PartRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_role
     *
     * @mbggenerated
     */
    int deleteByExample(PartRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_role
     *
     * @mbggenerated
     */
    @Delete({
        "delete from part_role",
        "where pid = #{pid,jdbcType=INTEGER}",
          "and rid = #{rid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(PartRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_role
     *
     * @mbggenerated
     */
    @Insert({
        "insert into part_role (pid, rid)",
        "values (#{pid,jdbcType=INTEGER}, #{rid,jdbcType=INTEGER})"
    })
    int insert(PartRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_role
     *
     * @mbggenerated
     */
    int insertSelective(PartRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_role
     *
     * @mbggenerated
     */
    List<PartRoleKey> selectByExample(PartRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PartRoleKey record, @Param("example") PartRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PartRoleKey record, @Param("example") PartRoleExample example);
}