package cn.sirbox.dao;

import cn.sirbox.model.UserExtend;
import cn.sirbox.model.UserExtendExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserExtendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    int countByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    int deleteByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_extend",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_extend (id, uid, ",
        "usex, uage, uemail, ",
        "imgsrc, uphone, ",
        "ubirthday, upost, ",
        "uunit, ucard, upolitical, ",
        "ugraduation, umajor, ",
        "uintroduction, urealname, ",
        "uaddress)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER}, ",
        "#{usex,jdbcType=VARCHAR}, #{uage,jdbcType=INTEGER}, #{uemail,jdbcType=VARCHAR}, ",
        "#{imgsrc,jdbcType=VARCHAR}, #{uphone,jdbcType=VARCHAR}, ",
        "#{ubirthday,jdbcType=TIMESTAMP}, #{upost,jdbcType=VARCHAR}, ",
        "#{uunit,jdbcType=VARCHAR}, #{ucard,jdbcType=VARCHAR}, #{upolitical,jdbcType=VARCHAR}, ",
        "#{ugraduation,jdbcType=VARCHAR}, #{umajor,jdbcType=VARCHAR}, ",
        "#{uintroduction,jdbcType=VARCHAR}, #{urealname,jdbcType=VARCHAR}, ",
        "#{uaddress,jdbcType=VARCHAR})"
    })
    int insert(UserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    int insertSelective(UserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    List<UserExtend> selectByExample(UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, uid, usex, uage, uemail, imgsrc, uphone, ubirthday, upost, uunit, ucard, ",
        "upolitical, ugraduation, umajor, uintroduction, urealname, uaddress",
        "from user_extend",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserExtend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserExtend record, @Param("example") UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserExtend record, @Param("example") UserExtendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    @Update({
        "update user_extend",
        "set uid = #{uid,jdbcType=INTEGER},",
          "usex = #{usex,jdbcType=VARCHAR},",
          "uage = #{uage,jdbcType=INTEGER},",
          "uemail = #{uemail,jdbcType=VARCHAR},",
          "imgsrc = #{imgsrc,jdbcType=VARCHAR},",
          "uphone = #{uphone,jdbcType=VARCHAR},",
          "ubirthday = #{ubirthday,jdbcType=TIMESTAMP},",
          "upost = #{upost,jdbcType=VARCHAR},",
          "uunit = #{uunit,jdbcType=VARCHAR},",
          "ucard = #{ucard,jdbcType=VARCHAR},",
          "upolitical = #{upolitical,jdbcType=VARCHAR},",
          "ugraduation = #{ugraduation,jdbcType=VARCHAR},",
          "umajor = #{umajor,jdbcType=VARCHAR},",
          "uintroduction = #{uintroduction,jdbcType=VARCHAR},",
          "urealname = #{urealname,jdbcType=VARCHAR},",
          "uaddress = #{uaddress,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserExtend record);
}