package cn.sirbox.dao;

import cn.sirbox.model.UserLoggerExample;
import cn.sirbox.model.UserLoggerKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface UserLoggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_logger
     *
     * @mbggenerated
     */
    int countByExample(UserLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_logger
     *
     * @mbggenerated
     */
    int deleteByExample(UserLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_logger
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_logger",
        "where lid = #{lid,jdbcType=INTEGER}",
          "and uid = #{uid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UserLoggerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_logger
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_logger (lid, uid)",
        "values (#{lid,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER})"
    })
    int insert(UserLoggerKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_logger
     *
     * @mbggenerated
     */
    int insertSelective(UserLoggerKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_logger
     *
     * @mbggenerated
     */
    List<UserLoggerKey> selectByExample(UserLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_logger
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserLoggerKey record, @Param("example") UserLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_logger
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserLoggerKey record, @Param("example") UserLoggerExample example);
}