package cn.sirbox.dao;

import cn.sirbox.model.UserDeptExample;
import cn.sirbox.model.UserDeptKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface UserDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated
     */
    int countByExample(UserDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated
     */
    int deleteByExample(UserDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_dept",
        "where uid = #{uid,jdbcType=INTEGER}",
          "and did = #{did,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UserDeptKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_dept (uid, did)",
        "values (#{uid,jdbcType=INTEGER}, #{did,jdbcType=INTEGER})"
    })
    int insert(UserDeptKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated
     */
    int insertSelective(UserDeptKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated
     */
    List<UserDeptKey> selectByExample(UserDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserDeptKey record, @Param("example") UserDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dept
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserDeptKey record, @Param("example") UserDeptExample example);
}