package cn.sirbox.dao;

import cn.sirbox.model.UserQ;
import cn.sirbox.model.UserQExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface UserQMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    int countByExample(UserQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    int deleteByExample(UserQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_q",
        "where qid = #{qid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer qid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_q (qid, qname, ",
        "qpassword, qage, ",
        "qsex, qbrithday)",
        "values (#{qid,jdbcType=INTEGER}, #{qname,jdbcType=VARCHAR}, ",
        "#{qpassword,jdbcType=VARCHAR}, #{qage,jdbcType=VARCHAR}, ",
        "#{qsex,jdbcType=VARCHAR}, #{qbrithday,jdbcType=VARCHAR})"
    })
    int insert(UserQ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    int insertSelective(UserQ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    List<UserQ> selectByExample(UserQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "qid, qname, qpassword, qage, qsex, qbrithday",
        "from user_q",
        "where qid = #{qid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserQ selectByPrimaryKey(Integer qid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserQ record, @Param("example") UserQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserQ record, @Param("example") UserQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserQ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    @Update({
        "update user_q",
        "set qname = #{qname,jdbcType=VARCHAR},",
          "qpassword = #{qpassword,jdbcType=VARCHAR},",
          "qage = #{qage,jdbcType=VARCHAR},",
          "qsex = #{qsex,jdbcType=VARCHAR},",
          "qbrithday = #{qbrithday,jdbcType=VARCHAR}",
        "where qid = #{qid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserQ record);
}