package cn.sirbox.dao;

import cn.sirbox.model.UserOrderExample;
import cn.sirbox.model.UserOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int countByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int deleteByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_order",
        "where oid = #{oid,jdbcType=INTEGER}",
          "and uid = #{uid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UserOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_order (oid, uid)",
        "values (#{oid,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER})"
    })
    int insert(UserOrderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int insertSelective(UserOrderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    List<UserOrderKey> selectByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserOrderKey record, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserOrderKey record, @Param("example") UserOrderExample example);
}