package cn.sirbox.dao;

import cn.sirbox.model.UserEnterpriseExample;
import cn.sirbox.model.UserEnterpriseKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface UserEnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise
     *
     * @mbggenerated
     */
    int countByExample(UserEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise
     *
     * @mbggenerated
     */
    int deleteByExample(UserEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_enterprise",
        "where eid = #{eid,jdbcType=INTEGER}",
          "and uid = #{uid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UserEnterpriseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_enterprise (eid, uid)",
        "values (#{eid,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER})"
    })
    int insert(UserEnterpriseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise
     *
     * @mbggenerated
     */
    int insertSelective(UserEnterpriseKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise
     *
     * @mbggenerated
     */
    List<UserEnterpriseKey> selectByExample(UserEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserEnterpriseKey record, @Param("example") UserEnterpriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_enterprise
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserEnterpriseKey record, @Param("example") UserEnterpriseExample example);
}