package cn.sirbox.model;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rid
     *
     * @mbggenerated
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rname
     *
     * @mbggenerated
     */
    private String rname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rstring
     *
     * @mbggenerated
     */
    private String rstring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.enabled
     *
     * @mbggenerated
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rid
     *
     * @return the value of role.rid
     *
     * @mbggenerated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rid
     *
     * @param rid the value for role.rid
     *
     * @mbggenerated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rname
     *
     * @return the value of role.rname
     *
     * @mbggenerated
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rname
     *
     * @param rname the value for role.rname
     *
     * @mbggenerated
     */
    public void setRname(String rname) {
        this.rname = rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rstring
     *
     * @return the value of role.rstring
     *
     * @mbggenerated
     */
    public String getRstring() {
        return rstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rstring
     *
     * @param rstring the value for role.rstring
     *
     * @mbggenerated
     */
    public void setRstring(String rstring) {
        this.rstring = rstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.enabled
     *
     * @return the value of role.enabled
     *
     * @mbggenerated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.enabled
     *
     * @param enabled the value for role.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.createtime
     *
     * @return the value of role.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.createtime
     *
     * @param createtime the value for role.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.updatetime
     *
     * @return the value of role.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.updatetime
     *
     * @param updatetime the value for role.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}