package cn.sirbox.model;

public class Part {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.pname
     *
     * @mbggenerated
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column part.pid
     *
     * @return the value of part.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column part.pid
     *
     * @param pid the value for part.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column part.pname
     *
     * @return the value of part.pname
     *
     * @mbggenerated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column part.pname
     *
     * @param pname the value for part.pname
     *
     * @mbggenerated
     */
    public void setPname(String pname) {
        this.pname = pname;
    }
}