package cn.sirbox.model;

public class UserDeptKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dept.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dept.did
     *
     * @mbggenerated
     */
    private Integer did;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dept.uid
     *
     * @return the value of user_dept.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dept.uid
     *
     * @param uid the value for user_dept.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dept.did
     *
     * @return the value of user_dept.did
     *
     * @mbggenerated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dept.did
     *
     * @param did the value for user_dept.did
     *
     * @mbggenerated
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}