package cn.sirbox.model;

public class UserEnterpriseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_enterprise.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise.eid
     *
     * @return the value of user_enterprise.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise.eid
     *
     * @param eid the value for user_enterprise.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_enterprise.uid
     *
     * @return the value of user_enterprise.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_enterprise.uid
     *
     * @param uid the value for user_enterprise.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}