package cn.sirbox.model;

import java.util.ArrayList;
import java.util.List;

public class UserQExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_q
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_q
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_q
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public UserQExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_q
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQidIsNull() {
            addCriterion("qid is null");
            return (Criteria) this;
        }

        public Criteria andQidIsNotNull() {
            addCriterion("qid is not null");
            return (Criteria) this;
        }

        public Criteria andQidEqualTo(Integer value) {
            addCriterion("qid =", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidNotEqualTo(Integer value) {
            addCriterion("qid <>", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidGreaterThan(Integer value) {
            addCriterion("qid >", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidGreaterThanOrEqualTo(Integer value) {
            addCriterion("qid >=", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidLessThan(Integer value) {
            addCriterion("qid <", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidLessThanOrEqualTo(Integer value) {
            addCriterion("qid <=", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidIn(List<Integer> values) {
            addCriterion("qid in", values, "qid");
            return (Criteria) this;
        }

        public Criteria andQidNotIn(List<Integer> values) {
            addCriterion("qid not in", values, "qid");
            return (Criteria) this;
        }

        public Criteria andQidBetween(Integer value1, Integer value2) {
            addCriterion("qid between", value1, value2, "qid");
            return (Criteria) this;
        }

        public Criteria andQidNotBetween(Integer value1, Integer value2) {
            addCriterion("qid not between", value1, value2, "qid");
            return (Criteria) this;
        }

        public Criteria andQnameIsNull() {
            addCriterion("qname is null");
            return (Criteria) this;
        }

        public Criteria andQnameIsNotNull() {
            addCriterion("qname is not null");
            return (Criteria) this;
        }

        public Criteria andQnameEqualTo(String value) {
            addCriterion("qname =", value, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameNotEqualTo(String value) {
            addCriterion("qname <>", value, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameGreaterThan(String value) {
            addCriterion("qname >", value, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameGreaterThanOrEqualTo(String value) {
            addCriterion("qname >=", value, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameLessThan(String value) {
            addCriterion("qname <", value, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameLessThanOrEqualTo(String value) {
            addCriterion("qname <=", value, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameLike(String value) {
            addCriterion("qname like", value, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameNotLike(String value) {
            addCriterion("qname not like", value, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameIn(List<String> values) {
            addCriterion("qname in", values, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameNotIn(List<String> values) {
            addCriterion("qname not in", values, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameBetween(String value1, String value2) {
            addCriterion("qname between", value1, value2, "qname");
            return (Criteria) this;
        }

        public Criteria andQnameNotBetween(String value1, String value2) {
            addCriterion("qname not between", value1, value2, "qname");
            return (Criteria) this;
        }

        public Criteria andQpasswordIsNull() {
            addCriterion("qpassword is null");
            return (Criteria) this;
        }

        public Criteria andQpasswordIsNotNull() {
            addCriterion("qpassword is not null");
            return (Criteria) this;
        }

        public Criteria andQpasswordEqualTo(String value) {
            addCriterion("qpassword =", value, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordNotEqualTo(String value) {
            addCriterion("qpassword <>", value, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordGreaterThan(String value) {
            addCriterion("qpassword >", value, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("qpassword >=", value, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordLessThan(String value) {
            addCriterion("qpassword <", value, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordLessThanOrEqualTo(String value) {
            addCriterion("qpassword <=", value, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordLike(String value) {
            addCriterion("qpassword like", value, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordNotLike(String value) {
            addCriterion("qpassword not like", value, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordIn(List<String> values) {
            addCriterion("qpassword in", values, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordNotIn(List<String> values) {
            addCriterion("qpassword not in", values, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordBetween(String value1, String value2) {
            addCriterion("qpassword between", value1, value2, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQpasswordNotBetween(String value1, String value2) {
            addCriterion("qpassword not between", value1, value2, "qpassword");
            return (Criteria) this;
        }

        public Criteria andQageIsNull() {
            addCriterion("qage is null");
            return (Criteria) this;
        }

        public Criteria andQageIsNotNull() {
            addCriterion("qage is not null");
            return (Criteria) this;
        }

        public Criteria andQageEqualTo(String value) {
            addCriterion("qage =", value, "qage");
            return (Criteria) this;
        }

        public Criteria andQageNotEqualTo(String value) {
            addCriterion("qage <>", value, "qage");
            return (Criteria) this;
        }

        public Criteria andQageGreaterThan(String value) {
            addCriterion("qage >", value, "qage");
            return (Criteria) this;
        }

        public Criteria andQageGreaterThanOrEqualTo(String value) {
            addCriterion("qage >=", value, "qage");
            return (Criteria) this;
        }

        public Criteria andQageLessThan(String value) {
            addCriterion("qage <", value, "qage");
            return (Criteria) this;
        }

        public Criteria andQageLessThanOrEqualTo(String value) {
            addCriterion("qage <=", value, "qage");
            return (Criteria) this;
        }

        public Criteria andQageLike(String value) {
            addCriterion("qage like", value, "qage");
            return (Criteria) this;
        }

        public Criteria andQageNotLike(String value) {
            addCriterion("qage not like", value, "qage");
            return (Criteria) this;
        }

        public Criteria andQageIn(List<String> values) {
            addCriterion("qage in", values, "qage");
            return (Criteria) this;
        }

        public Criteria andQageNotIn(List<String> values) {
            addCriterion("qage not in", values, "qage");
            return (Criteria) this;
        }

        public Criteria andQageBetween(String value1, String value2) {
            addCriterion("qage between", value1, value2, "qage");
            return (Criteria) this;
        }

        public Criteria andQageNotBetween(String value1, String value2) {
            addCriterion("qage not between", value1, value2, "qage");
            return (Criteria) this;
        }

        public Criteria andQsexIsNull() {
            addCriterion("qsex is null");
            return (Criteria) this;
        }

        public Criteria andQsexIsNotNull() {
            addCriterion("qsex is not null");
            return (Criteria) this;
        }

        public Criteria andQsexEqualTo(String value) {
            addCriterion("qsex =", value, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexNotEqualTo(String value) {
            addCriterion("qsex <>", value, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexGreaterThan(String value) {
            addCriterion("qsex >", value, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexGreaterThanOrEqualTo(String value) {
            addCriterion("qsex >=", value, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexLessThan(String value) {
            addCriterion("qsex <", value, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexLessThanOrEqualTo(String value) {
            addCriterion("qsex <=", value, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexLike(String value) {
            addCriterion("qsex like", value, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexNotLike(String value) {
            addCriterion("qsex not like", value, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexIn(List<String> values) {
            addCriterion("qsex in", values, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexNotIn(List<String> values) {
            addCriterion("qsex not in", values, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexBetween(String value1, String value2) {
            addCriterion("qsex between", value1, value2, "qsex");
            return (Criteria) this;
        }

        public Criteria andQsexNotBetween(String value1, String value2) {
            addCriterion("qsex not between", value1, value2, "qsex");
            return (Criteria) this;
        }

        public Criteria andQbrithdayIsNull() {
            addCriterion("qbrithday is null");
            return (Criteria) this;
        }

        public Criteria andQbrithdayIsNotNull() {
            addCriterion("qbrithday is not null");
            return (Criteria) this;
        }

        public Criteria andQbrithdayEqualTo(String value) {
            addCriterion("qbrithday =", value, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayNotEqualTo(String value) {
            addCriterion("qbrithday <>", value, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayGreaterThan(String value) {
            addCriterion("qbrithday >", value, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayGreaterThanOrEqualTo(String value) {
            addCriterion("qbrithday >=", value, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayLessThan(String value) {
            addCriterion("qbrithday <", value, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayLessThanOrEqualTo(String value) {
            addCriterion("qbrithday <=", value, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayLike(String value) {
            addCriterion("qbrithday like", value, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayNotLike(String value) {
            addCriterion("qbrithday not like", value, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayIn(List<String> values) {
            addCriterion("qbrithday in", values, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayNotIn(List<String> values) {
            addCriterion("qbrithday not in", values, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayBetween(String value1, String value2) {
            addCriterion("qbrithday between", value1, value2, "qbrithday");
            return (Criteria) this;
        }

        public Criteria andQbrithdayNotBetween(String value1, String value2) {
            addCriterion("qbrithday not between", value1, value2, "qbrithday");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_q
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_q
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}