package cn.sirbox.model;

public class DeptEnterpriseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_enterprise.did
     *
     * @mbggenerated
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_enterprise.eid
     *
     * @mbggenerated
     */
    private Integer eid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_enterprise.did
     *
     * @return the value of dept_enterprise.did
     *
     * @mbggenerated
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_enterprise.did
     *
     * @param did the value for dept_enterprise.did
     *
     * @mbggenerated
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_enterprise.eid
     *
     * @return the value of dept_enterprise.eid
     *
     * @mbggenerated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_enterprise.eid
     *
     * @param eid the value for dept_enterprise.eid
     *
     * @mbggenerated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }
}