package cn.sirbox.model;

public class UserLoggerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_logger.lid
     *
     * @mbggenerated
     */
    private Integer lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_logger.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_logger.lid
     *
     * @return the value of user_logger.lid
     *
     * @mbggenerated
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_logger.lid
     *
     * @param lid the value for user_logger.lid
     *
     * @mbggenerated
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_logger.uid
     *
     * @return the value of user_logger.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_logger.uid
     *
     * @param uid the value for user_logger.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}