package cn.sirbox.model;

public class UserQ {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_q.qid
     *
     * @mbggenerated
     */
    private Integer qid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_q.qname
     *
     * @mbggenerated
     */
    private String qname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_q.qpassword
     *
     * @mbggenerated
     */
    private String qpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_q.qage
     *
     * @mbggenerated
     */
    private String qage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_q.qsex
     *
     * @mbggenerated
     */
    private String qsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_q.qbrithday
     *
     * @mbggenerated
     */
    private String qbrithday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_q.qid
     *
     * @return the value of user_q.qid
     *
     * @mbggenerated
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_q.qid
     *
     * @param qid the value for user_q.qid
     *
     * @mbggenerated
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_q.qname
     *
     * @return the value of user_q.qname
     *
     * @mbggenerated
     */
    public String getQname() {
        return qname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_q.qname
     *
     * @param qname the value for user_q.qname
     *
     * @mbggenerated
     */
    public void setQname(String qname) {
        this.qname = qname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_q.qpassword
     *
     * @return the value of user_q.qpassword
     *
     * @mbggenerated
     */
    public String getQpassword() {
        return qpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_q.qpassword
     *
     * @param qpassword the value for user_q.qpassword
     *
     * @mbggenerated
     */
    public void setQpassword(String qpassword) {
        this.qpassword = qpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_q.qage
     *
     * @return the value of user_q.qage
     *
     * @mbggenerated
     */
    public String getQage() {
        return qage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_q.qage
     *
     * @param qage the value for user_q.qage
     *
     * @mbggenerated
     */
    public void setQage(String qage) {
        this.qage = qage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_q.qsex
     *
     * @return the value of user_q.qsex
     *
     * @mbggenerated
     */
    public String getQsex() {
        return qsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_q.qsex
     *
     * @param qsex the value for user_q.qsex
     *
     * @mbggenerated
     */
    public void setQsex(String qsex) {
        this.qsex = qsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_q.qbrithday
     *
     * @return the value of user_q.qbrithday
     *
     * @mbggenerated
     */
    public String getQbrithday() {
        return qbrithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_q.qbrithday
     *
     * @param qbrithday the value for user_q.qbrithday
     *
     * @mbggenerated
     */
    public void setQbrithday(String qbrithday) {
        this.qbrithday = qbrithday;
    }
}