package cn.sirbox.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExtendExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public UserExtendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUsexIsNull() {
            addCriterion("usex is null");
            return (Criteria) this;
        }

        public Criteria andUsexIsNotNull() {
            addCriterion("usex is not null");
            return (Criteria) this;
        }

        public Criteria andUsexEqualTo(String value) {
            addCriterion("usex =", value, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexNotEqualTo(String value) {
            addCriterion("usex <>", value, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexGreaterThan(String value) {
            addCriterion("usex >", value, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexGreaterThanOrEqualTo(String value) {
            addCriterion("usex >=", value, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexLessThan(String value) {
            addCriterion("usex <", value, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexLessThanOrEqualTo(String value) {
            addCriterion("usex <=", value, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexLike(String value) {
            addCriterion("usex like", value, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexNotLike(String value) {
            addCriterion("usex not like", value, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexIn(List<String> values) {
            addCriterion("usex in", values, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexNotIn(List<String> values) {
            addCriterion("usex not in", values, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexBetween(String value1, String value2) {
            addCriterion("usex between", value1, value2, "usex");
            return (Criteria) this;
        }

        public Criteria andUsexNotBetween(String value1, String value2) {
            addCriterion("usex not between", value1, value2, "usex");
            return (Criteria) this;
        }

        public Criteria andUageIsNull() {
            addCriterion("uage is null");
            return (Criteria) this;
        }

        public Criteria andUageIsNotNull() {
            addCriterion("uage is not null");
            return (Criteria) this;
        }

        public Criteria andUageEqualTo(Integer value) {
            addCriterion("uage =", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotEqualTo(Integer value) {
            addCriterion("uage <>", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageGreaterThan(Integer value) {
            addCriterion("uage >", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageGreaterThanOrEqualTo(Integer value) {
            addCriterion("uage >=", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageLessThan(Integer value) {
            addCriterion("uage <", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageLessThanOrEqualTo(Integer value) {
            addCriterion("uage <=", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageIn(List<Integer> values) {
            addCriterion("uage in", values, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotIn(List<Integer> values) {
            addCriterion("uage not in", values, "uage");
            return (Criteria) this;
        }

        public Criteria andUageBetween(Integer value1, Integer value2) {
            addCriterion("uage between", value1, value2, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotBetween(Integer value1, Integer value2) {
            addCriterion("uage not between", value1, value2, "uage");
            return (Criteria) this;
        }

        public Criteria andUemailIsNull() {
            addCriterion("uemail is null");
            return (Criteria) this;
        }

        public Criteria andUemailIsNotNull() {
            addCriterion("uemail is not null");
            return (Criteria) this;
        }

        public Criteria andUemailEqualTo(String value) {
            addCriterion("uemail =", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotEqualTo(String value) {
            addCriterion("uemail <>", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailGreaterThan(String value) {
            addCriterion("uemail >", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailGreaterThanOrEqualTo(String value) {
            addCriterion("uemail >=", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLessThan(String value) {
            addCriterion("uemail <", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLessThanOrEqualTo(String value) {
            addCriterion("uemail <=", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLike(String value) {
            addCriterion("uemail like", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotLike(String value) {
            addCriterion("uemail not like", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailIn(List<String> values) {
            addCriterion("uemail in", values, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotIn(List<String> values) {
            addCriterion("uemail not in", values, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailBetween(String value1, String value2) {
            addCriterion("uemail between", value1, value2, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotBetween(String value1, String value2) {
            addCriterion("uemail not between", value1, value2, "uemail");
            return (Criteria) this;
        }

        public Criteria andImgsrcIsNull() {
            addCriterion("imgsrc is null");
            return (Criteria) this;
        }

        public Criteria andImgsrcIsNotNull() {
            addCriterion("imgsrc is not null");
            return (Criteria) this;
        }

        public Criteria andImgsrcEqualTo(String value) {
            addCriterion("imgsrc =", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcNotEqualTo(String value) {
            addCriterion("imgsrc <>", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcGreaterThan(String value) {
            addCriterion("imgsrc >", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcGreaterThanOrEqualTo(String value) {
            addCriterion("imgsrc >=", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcLessThan(String value) {
            addCriterion("imgsrc <", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcLessThanOrEqualTo(String value) {
            addCriterion("imgsrc <=", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcLike(String value) {
            addCriterion("imgsrc like", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcNotLike(String value) {
            addCriterion("imgsrc not like", value, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcIn(List<String> values) {
            addCriterion("imgsrc in", values, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcNotIn(List<String> values) {
            addCriterion("imgsrc not in", values, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcBetween(String value1, String value2) {
            addCriterion("imgsrc between", value1, value2, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andImgsrcNotBetween(String value1, String value2) {
            addCriterion("imgsrc not between", value1, value2, "imgsrc");
            return (Criteria) this;
        }

        public Criteria andUphoneIsNull() {
            addCriterion("uphone is null");
            return (Criteria) this;
        }

        public Criteria andUphoneIsNotNull() {
            addCriterion("uphone is not null");
            return (Criteria) this;
        }

        public Criteria andUphoneEqualTo(String value) {
            addCriterion("uphone =", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotEqualTo(String value) {
            addCriterion("uphone <>", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneGreaterThan(String value) {
            addCriterion("uphone >", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneGreaterThanOrEqualTo(String value) {
            addCriterion("uphone >=", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLessThan(String value) {
            addCriterion("uphone <", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLessThanOrEqualTo(String value) {
            addCriterion("uphone <=", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLike(String value) {
            addCriterion("uphone like", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotLike(String value) {
            addCriterion("uphone not like", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneIn(List<String> values) {
            addCriterion("uphone in", values, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotIn(List<String> values) {
            addCriterion("uphone not in", values, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneBetween(String value1, String value2) {
            addCriterion("uphone between", value1, value2, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotBetween(String value1, String value2) {
            addCriterion("uphone not between", value1, value2, "uphone");
            return (Criteria) this;
        }

        public Criteria andUbirthdayIsNull() {
            addCriterion("ubirthday is null");
            return (Criteria) this;
        }

        public Criteria andUbirthdayIsNotNull() {
            addCriterion("ubirthday is not null");
            return (Criteria) this;
        }

        public Criteria andUbirthdayEqualTo(Date value) {
            addCriterion("ubirthday =", value, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayNotEqualTo(Date value) {
            addCriterion("ubirthday <>", value, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayGreaterThan(Date value) {
            addCriterion("ubirthday >", value, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("ubirthday >=", value, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayLessThan(Date value) {
            addCriterion("ubirthday <", value, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayLessThanOrEqualTo(Date value) {
            addCriterion("ubirthday <=", value, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayIn(List<Date> values) {
            addCriterion("ubirthday in", values, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayNotIn(List<Date> values) {
            addCriterion("ubirthday not in", values, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayBetween(Date value1, Date value2) {
            addCriterion("ubirthday between", value1, value2, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUbirthdayNotBetween(Date value1, Date value2) {
            addCriterion("ubirthday not between", value1, value2, "ubirthday");
            return (Criteria) this;
        }

        public Criteria andUpostIsNull() {
            addCriterion("upost is null");
            return (Criteria) this;
        }

        public Criteria andUpostIsNotNull() {
            addCriterion("upost is not null");
            return (Criteria) this;
        }

        public Criteria andUpostEqualTo(String value) {
            addCriterion("upost =", value, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostNotEqualTo(String value) {
            addCriterion("upost <>", value, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostGreaterThan(String value) {
            addCriterion("upost >", value, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostGreaterThanOrEqualTo(String value) {
            addCriterion("upost >=", value, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostLessThan(String value) {
            addCriterion("upost <", value, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostLessThanOrEqualTo(String value) {
            addCriterion("upost <=", value, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostLike(String value) {
            addCriterion("upost like", value, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostNotLike(String value) {
            addCriterion("upost not like", value, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostIn(List<String> values) {
            addCriterion("upost in", values, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostNotIn(List<String> values) {
            addCriterion("upost not in", values, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostBetween(String value1, String value2) {
            addCriterion("upost between", value1, value2, "upost");
            return (Criteria) this;
        }

        public Criteria andUpostNotBetween(String value1, String value2) {
            addCriterion("upost not between", value1, value2, "upost");
            return (Criteria) this;
        }

        public Criteria andUunitIsNull() {
            addCriterion("uunit is null");
            return (Criteria) this;
        }

        public Criteria andUunitIsNotNull() {
            addCriterion("uunit is not null");
            return (Criteria) this;
        }

        public Criteria andUunitEqualTo(String value) {
            addCriterion("uunit =", value, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitNotEqualTo(String value) {
            addCriterion("uunit <>", value, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitGreaterThan(String value) {
            addCriterion("uunit >", value, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitGreaterThanOrEqualTo(String value) {
            addCriterion("uunit >=", value, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitLessThan(String value) {
            addCriterion("uunit <", value, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitLessThanOrEqualTo(String value) {
            addCriterion("uunit <=", value, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitLike(String value) {
            addCriterion("uunit like", value, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitNotLike(String value) {
            addCriterion("uunit not like", value, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitIn(List<String> values) {
            addCriterion("uunit in", values, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitNotIn(List<String> values) {
            addCriterion("uunit not in", values, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitBetween(String value1, String value2) {
            addCriterion("uunit between", value1, value2, "uunit");
            return (Criteria) this;
        }

        public Criteria andUunitNotBetween(String value1, String value2) {
            addCriterion("uunit not between", value1, value2, "uunit");
            return (Criteria) this;
        }

        public Criteria andUcardIsNull() {
            addCriterion("ucard is null");
            return (Criteria) this;
        }

        public Criteria andUcardIsNotNull() {
            addCriterion("ucard is not null");
            return (Criteria) this;
        }

        public Criteria andUcardEqualTo(String value) {
            addCriterion("ucard =", value, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardNotEqualTo(String value) {
            addCriterion("ucard <>", value, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardGreaterThan(String value) {
            addCriterion("ucard >", value, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardGreaterThanOrEqualTo(String value) {
            addCriterion("ucard >=", value, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardLessThan(String value) {
            addCriterion("ucard <", value, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardLessThanOrEqualTo(String value) {
            addCriterion("ucard <=", value, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardLike(String value) {
            addCriterion("ucard like", value, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardNotLike(String value) {
            addCriterion("ucard not like", value, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardIn(List<String> values) {
            addCriterion("ucard in", values, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardNotIn(List<String> values) {
            addCriterion("ucard not in", values, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardBetween(String value1, String value2) {
            addCriterion("ucard between", value1, value2, "ucard");
            return (Criteria) this;
        }

        public Criteria andUcardNotBetween(String value1, String value2) {
            addCriterion("ucard not between", value1, value2, "ucard");
            return (Criteria) this;
        }

        public Criteria andUpoliticalIsNull() {
            addCriterion("upolitical is null");
            return (Criteria) this;
        }

        public Criteria andUpoliticalIsNotNull() {
            addCriterion("upolitical is not null");
            return (Criteria) this;
        }

        public Criteria andUpoliticalEqualTo(String value) {
            addCriterion("upolitical =", value, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalNotEqualTo(String value) {
            addCriterion("upolitical <>", value, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalGreaterThan(String value) {
            addCriterion("upolitical >", value, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalGreaterThanOrEqualTo(String value) {
            addCriterion("upolitical >=", value, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalLessThan(String value) {
            addCriterion("upolitical <", value, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalLessThanOrEqualTo(String value) {
            addCriterion("upolitical <=", value, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalLike(String value) {
            addCriterion("upolitical like", value, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalNotLike(String value) {
            addCriterion("upolitical not like", value, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalIn(List<String> values) {
            addCriterion("upolitical in", values, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalNotIn(List<String> values) {
            addCriterion("upolitical not in", values, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalBetween(String value1, String value2) {
            addCriterion("upolitical between", value1, value2, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUpoliticalNotBetween(String value1, String value2) {
            addCriterion("upolitical not between", value1, value2, "upolitical");
            return (Criteria) this;
        }

        public Criteria andUgraduationIsNull() {
            addCriterion("ugraduation is null");
            return (Criteria) this;
        }

        public Criteria andUgraduationIsNotNull() {
            addCriterion("ugraduation is not null");
            return (Criteria) this;
        }

        public Criteria andUgraduationEqualTo(String value) {
            addCriterion("ugraduation =", value, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationNotEqualTo(String value) {
            addCriterion("ugraduation <>", value, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationGreaterThan(String value) {
            addCriterion("ugraduation >", value, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationGreaterThanOrEqualTo(String value) {
            addCriterion("ugraduation >=", value, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationLessThan(String value) {
            addCriterion("ugraduation <", value, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationLessThanOrEqualTo(String value) {
            addCriterion("ugraduation <=", value, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationLike(String value) {
            addCriterion("ugraduation like", value, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationNotLike(String value) {
            addCriterion("ugraduation not like", value, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationIn(List<String> values) {
            addCriterion("ugraduation in", values, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationNotIn(List<String> values) {
            addCriterion("ugraduation not in", values, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationBetween(String value1, String value2) {
            addCriterion("ugraduation between", value1, value2, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUgraduationNotBetween(String value1, String value2) {
            addCriterion("ugraduation not between", value1, value2, "ugraduation");
            return (Criteria) this;
        }

        public Criteria andUmajorIsNull() {
            addCriterion("umajor is null");
            return (Criteria) this;
        }

        public Criteria andUmajorIsNotNull() {
            addCriterion("umajor is not null");
            return (Criteria) this;
        }

        public Criteria andUmajorEqualTo(String value) {
            addCriterion("umajor =", value, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorNotEqualTo(String value) {
            addCriterion("umajor <>", value, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorGreaterThan(String value) {
            addCriterion("umajor >", value, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorGreaterThanOrEqualTo(String value) {
            addCriterion("umajor >=", value, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorLessThan(String value) {
            addCriterion("umajor <", value, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorLessThanOrEqualTo(String value) {
            addCriterion("umajor <=", value, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorLike(String value) {
            addCriterion("umajor like", value, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorNotLike(String value) {
            addCriterion("umajor not like", value, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorIn(List<String> values) {
            addCriterion("umajor in", values, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorNotIn(List<String> values) {
            addCriterion("umajor not in", values, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorBetween(String value1, String value2) {
            addCriterion("umajor between", value1, value2, "umajor");
            return (Criteria) this;
        }

        public Criteria andUmajorNotBetween(String value1, String value2) {
            addCriterion("umajor not between", value1, value2, "umajor");
            return (Criteria) this;
        }

        public Criteria andUintroductionIsNull() {
            addCriterion("uintroduction is null");
            return (Criteria) this;
        }

        public Criteria andUintroductionIsNotNull() {
            addCriterion("uintroduction is not null");
            return (Criteria) this;
        }

        public Criteria andUintroductionEqualTo(String value) {
            addCriterion("uintroduction =", value, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionNotEqualTo(String value) {
            addCriterion("uintroduction <>", value, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionGreaterThan(String value) {
            addCriterion("uintroduction >", value, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionGreaterThanOrEqualTo(String value) {
            addCriterion("uintroduction >=", value, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionLessThan(String value) {
            addCriterion("uintroduction <", value, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionLessThanOrEqualTo(String value) {
            addCriterion("uintroduction <=", value, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionLike(String value) {
            addCriterion("uintroduction like", value, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionNotLike(String value) {
            addCriterion("uintroduction not like", value, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionIn(List<String> values) {
            addCriterion("uintroduction in", values, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionNotIn(List<String> values) {
            addCriterion("uintroduction not in", values, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionBetween(String value1, String value2) {
            addCriterion("uintroduction between", value1, value2, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUintroductionNotBetween(String value1, String value2) {
            addCriterion("uintroduction not between", value1, value2, "uintroduction");
            return (Criteria) this;
        }

        public Criteria andUrealnameIsNull() {
            addCriterion("urealname is null");
            return (Criteria) this;
        }

        public Criteria andUrealnameIsNotNull() {
            addCriterion("urealname is not null");
            return (Criteria) this;
        }

        public Criteria andUrealnameEqualTo(String value) {
            addCriterion("urealname =", value, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameNotEqualTo(String value) {
            addCriterion("urealname <>", value, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameGreaterThan(String value) {
            addCriterion("urealname >", value, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameGreaterThanOrEqualTo(String value) {
            addCriterion("urealname >=", value, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameLessThan(String value) {
            addCriterion("urealname <", value, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameLessThanOrEqualTo(String value) {
            addCriterion("urealname <=", value, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameLike(String value) {
            addCriterion("urealname like", value, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameNotLike(String value) {
            addCriterion("urealname not like", value, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameIn(List<String> values) {
            addCriterion("urealname in", values, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameNotIn(List<String> values) {
            addCriterion("urealname not in", values, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameBetween(String value1, String value2) {
            addCriterion("urealname between", value1, value2, "urealname");
            return (Criteria) this;
        }

        public Criteria andUrealnameNotBetween(String value1, String value2) {
            addCriterion("urealname not between", value1, value2, "urealname");
            return (Criteria) this;
        }

        public Criteria andUaddressIsNull() {
            addCriterion("uaddress is null");
            return (Criteria) this;
        }

        public Criteria andUaddressIsNotNull() {
            addCriterion("uaddress is not null");
            return (Criteria) this;
        }

        public Criteria andUaddressEqualTo(String value) {
            addCriterion("uaddress =", value, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressNotEqualTo(String value) {
            addCriterion("uaddress <>", value, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressGreaterThan(String value) {
            addCriterion("uaddress >", value, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressGreaterThanOrEqualTo(String value) {
            addCriterion("uaddress >=", value, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressLessThan(String value) {
            addCriterion("uaddress <", value, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressLessThanOrEqualTo(String value) {
            addCriterion("uaddress <=", value, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressLike(String value) {
            addCriterion("uaddress like", value, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressNotLike(String value) {
            addCriterion("uaddress not like", value, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressIn(List<String> values) {
            addCriterion("uaddress in", values, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressNotIn(List<String> values) {
            addCriterion("uaddress not in", values, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressBetween(String value1, String value2) {
            addCriterion("uaddress between", value1, value2, "uaddress");
            return (Criteria) this;
        }

        public Criteria andUaddressNotBetween(String value1, String value2) {
            addCriterion("uaddress not between", value1, value2, "uaddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_extend
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_extend
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}