package cn.sirbox.model;

public class UserOrderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.oid
     *
     * @mbggenerated
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.oid
     *
     * @return the value of user_order.oid
     *
     * @mbggenerated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.oid
     *
     * @param oid the value for user_order.oid
     *
     * @mbggenerated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.uid
     *
     * @return the value of user_order.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.uid
     *
     * @param uid the value for user_order.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}